language: python

python:
  - 3.7

git:
  depth: false
 
dist: bionic

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry --version

install:
  - poetry update -v
  - poetry show -v

before_script:
  - pytest --version
  - prospector --version
  - black --version
  - isort --version

script: 
  - pytest -v
  - prospector
  - black ./ --check
  - isort --recursive --check-only .

notifications:
  email: false